name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI (command-line interface)
        - Frontend (network parsers)
        - Compiler (optimization)
        - Backend (HDL generation)
        - Runtime (FPGA communication)
        - Build system
        - Documentation
        - Installation
        - Other
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Run command `spiking-fpga compile network.yaml`
        2. Set target to `artix7_35t`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: Copy and paste any error messages or logs
      render: shell
      placeholder: |
        Paste error messages, stack traces, or log output here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: Ubuntu 22.04 / Windows 11 / macOS 13
        - Python version: 3.10.8
        - Toolchain version: 0.1.0-dev
        - FPGA tools: Vivado 2024.1 / Quartus Prime 23.1
        - Hardware: Arty A7-35T
    validations:
      required: true

  - type: textarea
    id: minimal_example
    attributes:
      label: Minimal Example
      description: Provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        # Minimal code that reproduces the bug
        from spiking_fpga import compile_network, FPGATarget
        
        # Your code here...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Did this work in a previous version?
        - Are there any workarounds?
        - Related issues or discussions?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided a minimal reproducible example
          required: true
        - label: I have included relevant error messages and logs
          required: true