"""
HDLGenerator: Generates Verilog-like pseudocode for the mapped spiking neural network.
"""
from __future__ import annotations
from pathlib import Path
from spiking_fpga.graph import SpikingGraph
from spiking_fpga.mapper import MappingResult
from spiking_fpga.encoder import EncodedNetwork


VERILOG_HEADER = """\
// Auto-generated by Spiking-FPGA-Toolchain
// Model: {name}
// Cores: {n_cores}  Neurons: {n_neurons}  SpikeOps: {n_ops}
`timescale 1ns/1ps
"""

CORE_TEMPLATE = """\
// --- Core {core_id} ---
module snn_core_{core_id} #(
    parameter NEURON_COUNT = {neuron_count},
    parameter THRESHOLD = {threshold}
) (
    input wire clk,
    input wire rst,
    input wire [{spike_width}:0] spike_in,
    output reg [{spike_width}:0] spike_out
);
    reg [{membrane_width}:0] membrane [{neuron_count}:0];
    integer i;
    always @(posedge clk) begin
        if (rst) begin
            for (i=0; i<NEURON_COUNT; i=i+1) membrane[i] <= 0;
            spike_out <= 0;
        end else begin
            for (i=0; i<NEURON_COUNT; i=i+1) begin
                membrane[i] <= membrane[i] + spike_in[i];
                if (membrane[i] >= THRESHOLD) begin
                    spike_out[i] <= 1;
                    membrane[i] <= 0;  // reset after spike
                end else begin
                    spike_out[i] <= 0;
                end
            end
        end
    end
endmodule
"""

SYNAPSE_TEMPLATE = """\
// Synapse: {src_core}:{src_n} -> {dst_core}:{dst_n}  w={weight:.4f} d={delay}
// {op_type}: assign weight_{src_core}_{src_n}_to_{dst_core}_{dst_n} = {weight_fixed};
"""

TOP_TEMPLATE = """\
module snn_top_{name} (
    input wire clk,
    input wire rst,
    input wire [{input_width}:0] input_spikes,
    output wire [{output_width}:0] output_spikes
);
{core_instantiations}
endmodule
"""


class HDLGenerator:
    """Generates Verilog-like HDL pseudocode for a mapped SNN."""

    def __init__(self, membrane_bits: int = 16, weight_bits: int = 8):
        self.membrane_bits = membrane_bits
        self.weight_bits = weight_bits

    def generate(self, graph: SpikingGraph, mapping: MappingResult,
                 encoded: EncodedNetwork) -> str:
        """Generate complete HDL for the network."""
        lines = []
        lines.append(VERILOG_HEADER.format(
            name=graph.name,
            n_cores=mapping.total_cores,
            n_neurons=graph.total_neurons(),
            n_ops=encoded.total_ops
        ))

        # Emit core modules
        cores_seen = set()
        for alloc in mapping.core_allocations:
            if alloc.core_id in cores_seen:
                continue
            cores_seen.add(alloc.core_id)
            layer = graph.get_layer(alloc.layer_name)
            threshold = int(layer.threshold * (2**self.weight_bits)) if layer else 256
            n = alloc.size
            lines.append(CORE_TEMPLATE.format(
                core_id=alloc.core_id,
                neuron_count=n,
                threshold=threshold,
                spike_width=max(n - 1, 0),
                membrane_width=self.membrane_bits - 1
            ))

        # Emit synapse routing comments
        lines.append("// === Synapse Routing Table ===")
        for op in encoded.ops[:200]:  # cap for readability
            lines.append(SYNAPSE_TEMPLATE.format(
                src_core=op.src_core, src_n=op.src_neuron,
                dst_core=op.dst_core, dst_n=op.dst_neuron,
                weight=op.weight, delay=op.delay,
                op_type=op.op_type,
                weight_fixed=int(op.weight * 127)
            ))

        # Emit top-level module
        in_layer = graph.get_layer(graph.input_layer) if graph.input_layer else None
        out_layer = graph.get_layer(graph.output_layer) if graph.output_layer else None
        in_width = max((in_layer.neuron_count - 1), 0) if in_layer else 7
        out_width = max((out_layer.neuron_count - 1), 0) if out_layer else 7
        core_insts = "\n".join(
            f"    snn_core_{cid} #(.NEURON_COUNT({n})) core_{cid}(.clk(clk), .rst(rst), .spike_in(), .spike_out());"
            for cid, n in {a.core_id: a.size for a in mapping.core_allocations}.items()
        )
        lines.append(TOP_TEMPLATE.format(
            name=graph.name.replace("-", "_"),
            input_width=in_width,
            output_width=out_width,
            core_instantiations=core_insts
        ))

        return "\n".join(lines)

    def save(self, hdl: str, path: str) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(hdl)
        return p
